/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.vectorunit.VuBlueGojiHelper ----
jobject stub_VuBlueGojiHelper_getInstance_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.getInstance()LVuBlueGojiHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuBlueGojiHelper_debugLog_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.debugLog(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_VuBlueGojiHelper_initialize_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.initialize(LActivity;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jboolean stub_VuBlueGojiHelper_isSupported_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.isSupported()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_VuBlueGojiHelper_onDestroy_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuBlueGojiHelper_onPause_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuBlueGojiHelper_onResume_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuBlueGojiHelper_onStart_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuBlueGojiHelper_onStop_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuBlueGojiHelper_showOverlay_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuBlueGojiHelper.showOverlay()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.vectorunit.VuCloudSaveHelper ----
jobject stub_VuCloudSaveHelper_getInstance_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.getInstance()LVuCloudSaveHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuCloudSaveHelper_initialize_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.initialize(LActivity;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuCloudSaveHelper_onStateConflict_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.onStateConflict(ILjava/lang/String;[B[B)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jbyteArray arg2 = (jbyteArray) va_arg(args, jobject);
    jbyteArray arg3 = (jbyteArray) va_arg(args, jobject);
}

void stub_VuCloudSaveHelper_onStateLoaded_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.onStateLoaded(II[B)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jbyteArray arg2 = (jbyteArray) va_arg(args, jobject);
}

void stub_VuCloudSaveHelper_startCloudLoad_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.startCloudLoad()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuCloudSaveHelper_startCloudSave_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuCloudSaveHelper.startCloudSave([B)V called -- fill in from the real Java impl (jadx).");
    jbyteArray arg0 = (jbyteArray) va_arg(args, jobject);
}

// ---- com.vectorunit.VuGamePadHelper ----
jobject stub_VuGamePadHelper_getInstance_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.getInstance()LVuGamePadHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuGamePadHelper_initialize_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.initialize(LActivity;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jboolean stub_VuGamePadHelper_isDeviceConnected_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.isDeviceConnected(I)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return JNI_FALSE;
}

void stub_VuGamePadHelper_onDestroy_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuGamePadHelper_onKeyEvent_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onKeyEvent(LKeyEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuGamePadHelper_onMotionEvent_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onMotionEvent(LMotionEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuGamePadHelper_onPause_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuGamePadHelper_onResume_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuGamePadHelper_onStateEvent_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.onStateEvent(LStateEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuGamePadHelper_playMogaEffect_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuGamePadHelper.playMogaEffect(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

// ---- com.vectorunit.VuHttpHelper ----
jobject stub_VuHttpHelper_getInstance_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.getInstance()LVuHttpHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuHttpHelper_initialize_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.initialize(LActivity;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jobject stub_VuHttpHelper_openConnection_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.openConnection(Ljava/lang/String;)LHttpURLConnection; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

void stub_VuHttpHelper_sendRequest_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.sendRequest(LHttpURLConnection;[BI)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_VuHttpHelper_setRequestProperty_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.setRequestProperty(LHttpURLConnection;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_VuHttpHelper_setTimeoutMS_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuHttpHelper.setTimeoutMS(LHttpURLConnection;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

// ---- com.vectorunit.VuOnlineHelper ----
jobject stub_VuOnlineHelper_getInstance_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.getInstance()LVuOnlineHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuOnlineHelper_beginUserInitiatedSignIn_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.beginUserInitiatedSignIn()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_debugLog_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.debugLog(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_VuOnlineHelper_enableDebugLog_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.enableDebugLog(ZLjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_VuOnlineHelper_gameInitialize_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.gameInitialize()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_VuOnlineHelper_getAppStateClient_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.getAppStateClient()LAppStateClient; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_VuOnlineHelper_getGameHelper_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.getGameHelper()LGameHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_VuOnlineHelper_getGamesClient_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.getGamesClient()LGamesClient; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_VuOnlineHelper_getScores_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.getScores(Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_VuOnlineHelper_initialize_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.initialize(LActivity;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jboolean stub_VuOnlineHelper_isSignedIn_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.isSignedIn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_VuOnlineHelper_login_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.login()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_onAchievementUpdated_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onAchievementUpdated(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_VuOnlineHelper_onAchievementsLoaded_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onAchievementsLoaded(ILAchievementBuffer;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuOnlineHelper_onActivityResult_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuOnlineHelper_onLeaderboardScoresLoaded_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onLeaderboardScoresLoaded(ILLeaderboardBuffer;LLeaderboardScoreBuffer;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_VuOnlineHelper_onSignInFailed_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onSignInFailed()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_onSignInSucceeded_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onSignInSucceeded()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_onSignOutComplete_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onSignOutComplete()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_onStart_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_onStop_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_refreshAchievements_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.refreshAchievements()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_showAchievements_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.showAchievements()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_showAllLeaderboards_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.showAllLeaderboards()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_showDashboard_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.showDashboard()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_showLeaderboard_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.showLeaderboard(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_VuOnlineHelper_signOut_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.signOut()V called -- fill in from the real Java impl (jadx).");
}

void stub_VuOnlineHelper_submitScoreToLeaderboard_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.submitScoreToLeaderboard(Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_VuOnlineHelper_unlockAchievement_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.VuOnlineHelper.unlockAchievement(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

// ---- com.vectorunit.blue.Blue ----
void stub_Blue_onActivityResult_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Blue_onCreate_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Blue_onDestroy_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_Blue_onPause_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_Blue_onResume_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_Blue_onStart_66(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_Blue_onStop_67(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.vectorunit.blue.Blue.onStop()V called -- fill in from the real Java impl (jadx).");
}

// ---- org.fmod.FMODAudioDevice ----
jint stub_FMODAudioDevice_fetchChannelConfigFromCount_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.fetchChannelConfigFromCount(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_FMODAudioDevice_shutDown_69(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.shutDown()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_FMODAudioDevice_isMixing_70(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.isMixing()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_FMODAudioDevice_run_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.run()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_start_72(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.start()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_stop_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.stop()V called -- fill in from the real Java impl (jadx).");
}

