/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jobject stub_VuBlueGojiHelper_getInstance_0(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_debugLog_1(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_initialize_2(jmethodID id, va_list args);
extern jboolean stub_VuBlueGojiHelper_isSupported_3(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_onDestroy_4(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_onPause_5(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_onResume_6(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_onStart_7(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_onStop_8(jmethodID id, va_list args);
extern void stub_VuBlueGojiHelper_showOverlay_9(jmethodID id, va_list args);
extern jobject stub_VuCloudSaveHelper_getInstance_10(jmethodID id, va_list args);
extern void stub_VuCloudSaveHelper_initialize_11(jmethodID id, va_list args);
extern void stub_VuCloudSaveHelper_onStateConflict_12(jmethodID id, va_list args);
extern void stub_VuCloudSaveHelper_onStateLoaded_13(jmethodID id, va_list args);
extern void stub_VuCloudSaveHelper_startCloudLoad_14(jmethodID id, va_list args);
extern void stub_VuCloudSaveHelper_startCloudSave_15(jmethodID id, va_list args);
extern jobject stub_VuGamePadHelper_getInstance_16(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_initialize_17(jmethodID id, va_list args);
extern jboolean stub_VuGamePadHelper_isDeviceConnected_18(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onDestroy_19(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onKeyEvent_20(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onMotionEvent_21(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onPause_22(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onResume_23(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_onStateEvent_24(jmethodID id, va_list args);
extern void stub_VuGamePadHelper_playMogaEffect_25(jmethodID id, va_list args);
extern jobject stub_VuHttpHelper_getInstance_26(jmethodID id, va_list args);
extern void stub_VuHttpHelper_initialize_27(jmethodID id, va_list args);
extern jobject stub_VuHttpHelper_openConnection_28(jmethodID id, va_list args);
extern void stub_VuHttpHelper_sendRequest_29(jmethodID id, va_list args);
extern void stub_VuHttpHelper_setRequestProperty_30(jmethodID id, va_list args);
extern void stub_VuHttpHelper_setTimeoutMS_31(jmethodID id, va_list args);
extern jobject stub_VuOnlineHelper_getInstance_32(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_beginUserInitiatedSignIn_33(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_debugLog_34(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_enableDebugLog_35(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_gameInitialize_36(jmethodID id, va_list args);
extern jobject stub_VuOnlineHelper_getAppStateClient_37(jmethodID id, va_list args);
extern jobject stub_VuOnlineHelper_getGameHelper_38(jmethodID id, va_list args);
extern jobject stub_VuOnlineHelper_getGamesClient_39(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_getScores_40(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_initialize_41(jmethodID id, va_list args);
extern jboolean stub_VuOnlineHelper_isSignedIn_42(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_login_43(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onAchievementUpdated_44(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onAchievementsLoaded_45(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onActivityResult_46(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onLeaderboardScoresLoaded_47(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onSignInFailed_48(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onSignInSucceeded_49(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onSignOutComplete_50(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onStart_51(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_onStop_52(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_refreshAchievements_53(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_showAchievements_54(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_showAllLeaderboards_55(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_showDashboard_56(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_showLeaderboard_57(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_signOut_58(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_submitScoreToLeaderboard_59(jmethodID id, va_list args);
extern void stub_VuOnlineHelper_unlockAchievement_60(jmethodID id, va_list args);
extern void stub_Blue_onActivityResult_61(jmethodID id, va_list args);
extern void stub_Blue_onCreate_62(jmethodID id, va_list args);
extern void stub_Blue_onDestroy_63(jmethodID id, va_list args);
extern void stub_Blue_onPause_64(jmethodID id, va_list args);
extern void stub_Blue_onResume_65(jmethodID id, va_list args);
extern void stub_Blue_onStart_66(jmethodID id, va_list args);
extern void stub_Blue_onStop_67(jmethodID id, va_list args);
extern jint stub_FMODAudioDevice_fetchChannelConfigFromCount_68(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_shutDown_69(jmethodID id, va_list args);
extern jboolean stub_FMODAudioDevice_isMixing_70(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_run_71(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_start_72(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_stop_73(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "getInstance", METHOD_TYPE_OBJECT },  // com.vectorunit.VuBlueGojiHelper
    { 1, "debugLog", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 2, "initialize", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 3, "isSupported", METHOD_TYPE_BOOLEAN },  // com.vectorunit.VuBlueGojiHelper
    { 4, "onDestroy", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 5, "onPause", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 6, "onResume", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 7, "onStart", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 8, "onStop", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 9, "showOverlay", METHOD_TYPE_VOID },  // com.vectorunit.VuBlueGojiHelper
    { 10, "getInstance", METHOD_TYPE_OBJECT },  // com.vectorunit.VuCloudSaveHelper
    { 11, "initialize", METHOD_TYPE_VOID },  // com.vectorunit.VuCloudSaveHelper
    { 12, "onStateConflict", METHOD_TYPE_VOID },  // com.vectorunit.VuCloudSaveHelper
    { 13, "onStateLoaded", METHOD_TYPE_VOID },  // com.vectorunit.VuCloudSaveHelper
    { 14, "startCloudLoad", METHOD_TYPE_VOID },  // com.vectorunit.VuCloudSaveHelper
    { 15, "startCloudSave", METHOD_TYPE_VOID },  // com.vectorunit.VuCloudSaveHelper
    { 16, "getInstance", METHOD_TYPE_OBJECT },  // com.vectorunit.VuGamePadHelper
    { 17, "initialize", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 18, "isDeviceConnected", METHOD_TYPE_BOOLEAN },  // com.vectorunit.VuGamePadHelper
    { 19, "onDestroy", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 20, "onKeyEvent", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 21, "onMotionEvent", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 22, "onPause", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 23, "onResume", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 24, "onStateEvent", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 25, "playMogaEffect", METHOD_TYPE_VOID },  // com.vectorunit.VuGamePadHelper
    { 26, "getInstance", METHOD_TYPE_OBJECT },  // com.vectorunit.VuHttpHelper
    { 27, "initialize", METHOD_TYPE_VOID },  // com.vectorunit.VuHttpHelper
    { 28, "openConnection", METHOD_TYPE_OBJECT },  // com.vectorunit.VuHttpHelper
    { 29, "sendRequest", METHOD_TYPE_VOID },  // com.vectorunit.VuHttpHelper
    { 30, "setRequestProperty", METHOD_TYPE_VOID },  // com.vectorunit.VuHttpHelper
    { 31, "setTimeoutMS", METHOD_TYPE_VOID },  // com.vectorunit.VuHttpHelper
    { 32, "getInstance", METHOD_TYPE_OBJECT },  // com.vectorunit.VuOnlineHelper
    { 33, "beginUserInitiatedSignIn", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 34, "debugLog", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 35, "enableDebugLog", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 36, "gameInitialize", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 37, "getAppStateClient", METHOD_TYPE_OBJECT },  // com.vectorunit.VuOnlineHelper
    { 38, "getGameHelper", METHOD_TYPE_OBJECT },  // com.vectorunit.VuOnlineHelper
    { 39, "getGamesClient", METHOD_TYPE_OBJECT },  // com.vectorunit.VuOnlineHelper
    { 40, "getScores", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 41, "initialize", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 42, "isSignedIn", METHOD_TYPE_BOOLEAN },  // com.vectorunit.VuOnlineHelper
    { 43, "login", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 44, "onAchievementUpdated", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 45, "onAchievementsLoaded", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 46, "onActivityResult", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 47, "onLeaderboardScoresLoaded", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 48, "onSignInFailed", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 49, "onSignInSucceeded", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 50, "onSignOutComplete", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 51, "onStart", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 52, "onStop", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 53, "refreshAchievements", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 54, "showAchievements", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 55, "showAllLeaderboards", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 56, "showDashboard", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 57, "showLeaderboard", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 58, "signOut", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 59, "submitScoreToLeaderboard", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 60, "unlockAchievement", METHOD_TYPE_VOID },  // com.vectorunit.VuOnlineHelper
    { 61, "onActivityResult", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 62, "onCreate", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 63, "onDestroy", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 64, "onPause", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 65, "onResume", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 66, "onStart", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 67, "onStop", METHOD_TYPE_VOID },  // com.vectorunit.blue.Blue
    { 68, "fetchChannelConfigFromCount", METHOD_TYPE_INT },  // org.fmod.FMODAudioDevice
    { 69, "shutDown", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 70, "isMixing", METHOD_TYPE_BOOLEAN },  // org.fmod.FMODAudioDevice
    { 71, "run", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 72, "start", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 73, "stop", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 0, stub_VuBlueGojiHelper_getInstance_0 },
    { 10, stub_VuCloudSaveHelper_getInstance_10 },
    { 16, stub_VuGamePadHelper_getInstance_16 },
    { 26, stub_VuHttpHelper_getInstance_26 },
    { 28, stub_VuHttpHelper_openConnection_28 },
    { 32, stub_VuOnlineHelper_getInstance_32 },
    { 37, stub_VuOnlineHelper_getAppStateClient_37 },
    { 38, stub_VuOnlineHelper_getGameHelper_38 },
    { 39, stub_VuOnlineHelper_getGamesClient_39 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 1, stub_VuBlueGojiHelper_debugLog_1 },
    { 2, stub_VuBlueGojiHelper_initialize_2 },
    { 4, stub_VuBlueGojiHelper_onDestroy_4 },
    { 5, stub_VuBlueGojiHelper_onPause_5 },
    { 6, stub_VuBlueGojiHelper_onResume_6 },
    { 7, stub_VuBlueGojiHelper_onStart_7 },
    { 8, stub_VuBlueGojiHelper_onStop_8 },
    { 9, stub_VuBlueGojiHelper_showOverlay_9 },
    { 11, stub_VuCloudSaveHelper_initialize_11 },
    { 12, stub_VuCloudSaveHelper_onStateConflict_12 },
    { 13, stub_VuCloudSaveHelper_onStateLoaded_13 },
    { 14, stub_VuCloudSaveHelper_startCloudLoad_14 },
    { 15, stub_VuCloudSaveHelper_startCloudSave_15 },
    { 17, stub_VuGamePadHelper_initialize_17 },
    { 19, stub_VuGamePadHelper_onDestroy_19 },
    { 20, stub_VuGamePadHelper_onKeyEvent_20 },
    { 21, stub_VuGamePadHelper_onMotionEvent_21 },
    { 22, stub_VuGamePadHelper_onPause_22 },
    { 23, stub_VuGamePadHelper_onResume_23 },
    { 24, stub_VuGamePadHelper_onStateEvent_24 },
    { 25, stub_VuGamePadHelper_playMogaEffect_25 },
    { 27, stub_VuHttpHelper_initialize_27 },
    { 29, stub_VuHttpHelper_sendRequest_29 },
    { 30, stub_VuHttpHelper_setRequestProperty_30 },
    { 31, stub_VuHttpHelper_setTimeoutMS_31 },
    { 33, stub_VuOnlineHelper_beginUserInitiatedSignIn_33 },
    { 34, stub_VuOnlineHelper_debugLog_34 },
    { 35, stub_VuOnlineHelper_enableDebugLog_35 },
    { 36, stub_VuOnlineHelper_gameInitialize_36 },
    { 40, stub_VuOnlineHelper_getScores_40 },
    { 41, stub_VuOnlineHelper_initialize_41 },
    { 43, stub_VuOnlineHelper_login_43 },
    { 44, stub_VuOnlineHelper_onAchievementUpdated_44 },
    { 45, stub_VuOnlineHelper_onAchievementsLoaded_45 },
    { 46, stub_VuOnlineHelper_onActivityResult_46 },
    { 47, stub_VuOnlineHelper_onLeaderboardScoresLoaded_47 },
    { 48, stub_VuOnlineHelper_onSignInFailed_48 },
    { 49, stub_VuOnlineHelper_onSignInSucceeded_49 },
    { 50, stub_VuOnlineHelper_onSignOutComplete_50 },
    { 51, stub_VuOnlineHelper_onStart_51 },
    { 52, stub_VuOnlineHelper_onStop_52 },
    { 53, stub_VuOnlineHelper_refreshAchievements_53 },
    { 54, stub_VuOnlineHelper_showAchievements_54 },
    { 55, stub_VuOnlineHelper_showAllLeaderboards_55 },
    { 56, stub_VuOnlineHelper_showDashboard_56 },
    { 57, stub_VuOnlineHelper_showLeaderboard_57 },
    { 58, stub_VuOnlineHelper_signOut_58 },
    { 59, stub_VuOnlineHelper_submitScoreToLeaderboard_59 },
    { 60, stub_VuOnlineHelper_unlockAchievement_60 },
    { 61, stub_Blue_onActivityResult_61 },
    { 62, stub_Blue_onCreate_62 },
    { 63, stub_Blue_onDestroy_63 },
    { 64, stub_Blue_onPause_64 },
    { 65, stub_Blue_onResume_65 },
    { 66, stub_Blue_onStart_66 },
    { 67, stub_Blue_onStop_67 },
    { 69, stub_FMODAudioDevice_shutDown_69 },
    { 71, stub_FMODAudioDevice_run_71 },
    { 72, stub_FMODAudioDevice_start_72 },
    { 73, stub_FMODAudioDevice_stop_73 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 3, stub_VuBlueGojiHelper_isSupported_3 },
    { 18, stub_VuGamePadHelper_isDeviceConnected_18 },
    { 42, stub_VuOnlineHelper_isSignedIn_42 },
    { 70, stub_FMODAudioDevice_isMixing_70 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 68, stub_FMODAudioDevice_fetchChannelConfigFromCount_68 },
};

